baseURL = "https://myshell.co.uk/"
languageCode = "en-gb"
title = "myshell.co.uk"
enableRobotsTXT = true
theme = "terminal"
paginate = 10
# enableGitInfo = true
disqusShortname = "myshell"

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  # favicon = "favicon.ico"
  updatedDatePrefix = "Updated"
  # oneHeadingSize = true # default
  readingTime = true 
  # Toc = false # default
  # TocTitle = "Table of Contents" # default

  dateFormat = "2 Jan 2006"
  hideDefaultCredit = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  [permalinks.page]
    posts = "/blog/:year/:month/:slug/"
  [permalinks.section]
    posts = "/blog/"

[languages]
  [languages.en]
    languageName = "English"
    copyright = '<a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank"> Some rights reserved.</a>'

    [languages.en.params]
      subtitle = "Techie blog"
      owner = ""
      keywords = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

    [languages.en.params.logo]
      logoText = "myshell.co.uk"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        pageRef = "/about"
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "Résumé"
        url = "https://sebastiansobczynski.com"

[module]
  replacements = "github.com/s-sebastian/hugo-theme-terminal -> terminal"
[[module.imports]]
  path = "github.com/s-sebastian/hugo-theme-terminal"

[imaging]
  quality = 100
