baseurl = "https://myshell.co.uk/"
config = "config.toml"
languageCode = "en-gb"
MetaDataFormat = "toml"
title = "myshell.co.uk"
paginate = 20
#publishdir = ""

[blackfriday]
  plainIdAnchors = true

[params]
  author = "Sebastian"
  ga = true
  disqus = "myshell"
  DateForm = "Mon, Jan 2, 2006"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  Name = "Résumé"
  Weight = -2
  Identifier = "cv"
  URL = "http://sebastiansobczynski.com"

[[menu.main]]
  Name = "About Me"
  Weight = -1
  Identifier = "about"
  URL = "/about/"
